apiVersion: v1
kind: Pod
metadata:
  name: governance-dev-pod
  annotations:
    io.podman.annotations.userns: "keep-id"
spec:
  containers:
  - name: web-server
    image: docker.io/library/caddy:2-alpine
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext:
      seLinuxOptions:
        type: spc_t
    volumeMounts:
    - name: html-storage
      mountPath: /usr/share/caddy
    - name: config-storage
      mountPath: /var/www/config
    - name: caddy-config
      mountPath: /etc/caddy/Caddyfile
  volumes:
  - name: html-storage
    hostPath:
      path: ./public
      type: Directory
  - name: config-storage
    hostPath:
      path: ./config
      type: Directory
  - name: caddy-config
    hostPath:
      path: ./Caddyfile
      type: File